const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email =""
global.location="Taraba,Nigeria."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://www.peakpx.com/en/hd-wallpaper-desktop-fsqau.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "2348107052326" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2348107052326";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '4',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,null";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" ,
  
  author : process.env.PACK_AUTHER|| "JOSEPH-CM",
  packname: process.env.PACK_NAME || "STICKER",
  botname : process.env.BOT_NAME  || "JOSEPH-MD",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_13_37_06_17_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDgsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjMsXG4gICAgICAgIDQsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTUsXG4gICAgICAgIDI1NSxcbiAgICAgICAgNDcsXG4gICAgICAgIDc2LFxuICAgICAgICAxNTMsXG4gICAgICAgIDcwLFxuICAgICAgICA3NixcbiAgICAgICAgMTg5LFxuICAgICAgICAxMTEsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTAxLFxuICAgICAgICAyNDYsXG4gICAgICAgIDY4LFxuICAgICAgICAxMzksXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTc0LFxuICAgICAgICA0NixcbiAgICAgICAgNTMsXG4gICAgICAgIDIyNyxcbiAgICAgICAgNjEsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMzMsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjQ2LFxuICAgICAgICA5NixcbiAgICAgICAgMjA5LFxuICAgICAgICA3NFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA1MixcbiAgICAgICAgMTI2LFxuICAgICAgICAxMjQsXG4gICAgICAgIDExMCxcbiAgICAgICAgODYsXG4gICAgICAgIDU3LFxuICAgICAgICAxMzUsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTUxLFxuICAgICAgICA2OSxcbiAgICAgICAgNzcsXG4gICAgICAgIDQ5LFxuICAgICAgICA4MyxcbiAgICAgICAgMTM0LFxuICAgICAgICAxMzEsXG4gICAgICAgIDgyLFxuICAgICAgICAxNTgsXG4gICAgICAgIDM2LFxuICAgICAgICAxMjAsXG4gICAgICAgIDE4NSxcbiAgICAgICAgNTcsXG4gICAgICAgIDg1LFxuICAgICAgICAyNyxcbiAgICAgICAgMjA2LFxuICAgICAgICAxNjgsXG4gICAgICAgIDMwLFxuICAgICAgICAxMzcsXG4gICAgICAgIDE5NSxcbiAgICAgICAgODIsXG4gICAgICAgIDIwNyxcbiAgICAgICAgNDMsXG4gICAgICAgIDk4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNDQsXG4gICAgICAgIDkyLFxuICAgICAgICA3MSxcbiAgICAgICAgMjEsXG4gICAgICAgIDIwNCxcbiAgICAgICAgODUsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTMwLFxuICAgICAgICAxMzksXG4gICAgICAgIDc5LFxuICAgICAgICAxMzEsXG4gICAgICAgIDk5LFxuICAgICAgICAxMSxcbiAgICAgICAgMjI5LFxuICAgICAgICAxNDMsXG4gICAgICAgIDE0OSxcbiAgICAgICAgNTcsXG4gICAgICAgIDQyLFxuICAgICAgICAzOSxcbiAgICAgICAgMTg2LFxuICAgICAgICAxMyxcbiAgICAgICAgMTc5LFxuICAgICAgICAyMzUsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTQ2LFxuICAgICAgICAxODgsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMyxcbiAgICAgICAgMjcsXG4gICAgICAgIDIxNixcbiAgICAgICAgNjksXG4gICAgICAgIDgxXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjYsXG4gICAgICAgIDEyMyxcbiAgICAgICAgODEsXG4gICAgICAgIDIzOSxcbiAgICAgICAgODIsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMjI5LFxuICAgICAgICAyNTMsXG4gICAgICAgIDc2LFxuICAgICAgICAyMzcsXG4gICAgICAgIDEyMSxcbiAgICAgICAgNTEsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTEsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTU5LFxuICAgICAgICAyMjksXG4gICAgICAgIDYxLFxuICAgICAgICAyMzIsXG4gICAgICAgIDU0LFxuICAgICAgICAyNDUsXG4gICAgICAgIDExMyxcbiAgICAgICAgNTgsXG4gICAgICAgIDUzLFxuICAgICAgICAxNjIsXG4gICAgICAgIDIzLFxuICAgICAgICAzMSxcbiAgICAgICAgOTksXG4gICAgICAgIDYsXG4gICAgICAgIDIyMixcbiAgICAgICAgMzRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2OCxcbiAgICAgICAgNjMsXG4gICAgICAgIDEzNSxcbiAgICAgICAgNjksXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNyxcbiAgICAgICAgMTMsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTkyLFxuICAgICAgICAxMzcsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTQ4LFxuICAgICAgICA4MCxcbiAgICAgICAgMjQzLFxuICAgICAgICA4NSxcbiAgICAgICAgNTQsXG4gICAgICAgIDg1LFxuICAgICAgICAzMSxcbiAgICAgICAgMjI4LFxuICAgICAgICAxMjAsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTQ1LFxuICAgICAgICA5MSxcbiAgICAgICAgNDAsXG4gICAgICAgIDE0LFxuICAgICAgICAxOTEsXG4gICAgICAgIDYzLFxuICAgICAgICAxNDEsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTI1LFxuICAgICAgICA3OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2NSxcbiAgICAgICAgMzcsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTcyLFxuICAgICAgICA2LFxuICAgICAgICAxNTEsXG4gICAgICAgIDIyMyxcbiAgICAgICAgODksXG4gICAgICAgIDg3LFxuICAgICAgICAxMDIsXG4gICAgICAgIDEwLFxuICAgICAgICA3NSxcbiAgICAgICAgMTE2LFxuICAgICAgICAzNCxcbiAgICAgICAgMTAwLFxuICAgICAgICA1NCxcbiAgICAgICAgMjA3LFxuICAgICAgICAyMTMsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMjE4LFxuICAgICAgICAyMjAsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMixcbiAgICAgICAgMTA1LFxuICAgICAgICAxNTAsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTM4LFxuICAgICAgICAxODQsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTUyLFxuICAgICAgICAxODYsXG4gICAgICAgIDEyNVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMzgsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDEyNixcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMixcbiAgICAgICAgICA2OCxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgMTEwXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDMsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgNCxcbiAgICAgICAgICAyMCxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDQxXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM5LFxuICAgICAgICAxNjAsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjAzLFxuICAgICAgICA5NyxcbiAgICAgICAgMTYxLFxuICAgICAgICAxNDUsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTk4LFxuICAgICAgICAxNzIsXG4gICAgICAgIDI1MyxcbiAgICAgICAgOTcsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTUwLFxuICAgICAgICAxMTUsXG4gICAgICAgIDQ5LFxuICAgICAgICAxMjIsXG4gICAgICAgIDY1LFxuICAgICAgICA0MixcbiAgICAgICAgMTQsXG4gICAgICAgIDExNyxcbiAgICAgICAgNzIsXG4gICAgICAgIDE3NSxcbiAgICAgICAgOTcsXG4gICAgICAgIDM0LFxuICAgICAgICA0MSxcbiAgICAgICAgMjQxLFxuICAgICAgICA1OCxcbiAgICAgICAgMjYsXG4gICAgICAgIDE0MCxcbiAgICAgICAgNTIsXG4gICAgICAgIDE4LFxuICAgICAgICAyMDMsXG4gICAgICAgIDEzOCxcbiAgICAgICAgNDcsXG4gICAgICAgIDE5LFxuICAgICAgICA3NyxcbiAgICAgICAgOTcsXG4gICAgICAgIDM1LFxuICAgICAgICA2NSxcbiAgICAgICAgNixcbiAgICAgICAgMTgzLFxuICAgICAgICAyLFxuICAgICAgICAxNzYsXG4gICAgICAgIDM4LFxuICAgICAgICAxMjQsXG4gICAgICAgIDEyLFxuICAgICAgICAyMjcsXG4gICAgICAgIDEyMCxcbiAgICAgICAgOTcsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTAwLFxuICAgICAgICA2NCxcbiAgICAgICAgMTkwLFxuICAgICAgICAxMzEsXG4gICAgICAgIDg0LFxuICAgICAgICA1MyxcbiAgICAgICAgMjE5LFxuICAgICAgICAxMTksXG4gICAgICAgIDQ2LFxuICAgICAgICAyMzksXG4gICAgICAgIDI5LFxuICAgICAgICAxNzAsXG4gICAgICAgIDE0MVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTQ1LFxuICBcImFkdlNlY3JldEtleVwiOiBcImNyblRwZjRITzEwcW5OME4ra3JqdE90aHpIRTlBeGltUkE2akV2eDlqcGM9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0ODEwNzA1MjMyNkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMEU2N0QwRThFMzY3MUY4NUVBMjg3N0UwRUQzMTM5MEFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE4NjMxNDY2XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0ODEwNzA1MjMyNkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiRTI0NjYzQjRGRUZBRjMyMEJDNDREQzQyRUNGRkQxMzZcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE4NjMxNDY2XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIkRKaDdJQXI4UU5XRjlGZlpoQzVvY1FcIixcbiAgXCJwaG9uZUlkXCI6IFwiM2I0MDY4MDMtYTYzOS00N2MyLWEwZDAtZTQ0NGQwZjQ5MGE2XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE5MSxcbiAgICAgIDE3NCxcbiAgICAgIDEzNSxcbiAgICAgIDIwNCxcbiAgICAgIDE3MSxcbiAgICAgIDg0LFxuICAgICAgMjIzLFxuICAgICAgMTU3LFxuICAgICAgMjUyLFxuICAgICAgMTAsXG4gICAgICAxMDAsXG4gICAgICAyMzgsXG4gICAgICAyNSxcbiAgICAgIDEzMSxcbiAgICAgIDM2LFxuICAgICAgMzEsXG4gICAgICAyNTUsXG4gICAgICA4MixcbiAgICAgIDEzLFxuICAgICAgMTQ3XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA2MyxcbiAgICAgIDIxNCxcbiAgICAgIDE5MSxcbiAgICAgIDE0OSxcbiAgICAgIDE0NSxcbiAgICAgIDExNSxcbiAgICAgIDIyLFxuICAgICAgNTYsXG4gICAgICA0MixcbiAgICAgIDE4OSxcbiAgICAgIDEyNSxcbiAgICAgIDE0MixcbiAgICAgIDEwNixcbiAgICAgIDE4NixcbiAgICAgIDIyMixcbiAgICAgIDI1NSxcbiAgICAgIDIzLFxuICAgICAgMTIsXG4gICAgICAxMTUsXG4gICAgICAxMzZcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNMdUxpZThERUtMNHdMTUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjlZV3VoSXFJU2lGWmRCeGpTQzZPRHlDQ1EwdXlEVEpRcFVJMUV0L2E0Q2c9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwibUpmVFJIdTgxSmtQSjFMajNGcnpHWjBjdVNsMzJvdklJbC9vTVJ5cGlOS1k1eTN3MjEyenZDYWUxbzlzV1NOeXowY2tMaFg2dzZxTW5YKzRKamZwQ0E9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwid3VUd0RzNVA4TFNYYUhjTjhSTUd3eUlUN3Y1Vmk2ZWl4aHlSQkFqKzRMTU9jQWJRZ3RHNzAwakdic256bzlpREpHOVBHdGJla0I1amwyWTBlR1hWZ0E9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ4MTA3MDUyMzI2OjE1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiSuG7jMyBUzNQSCBNQURVS0FcIixcbiAgICBcImxpZFwiOiBcIjE3NDE5OTk5Nzk5NzE3MjoxNUBsaWRcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDgxMDcwNTIzMjY6MTVAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICAxMzIsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMjgsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDQwXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MTg2MzE0NjIsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFPekZcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU96Ri5qc29uIjogIntcImtleURhdGFcIjpcIm5qWjBaejFaNEQ1ejlNWllyeEFjOStyR1JnMWNJOXcwd2c3V1VEQXl3YUk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTAzODIzOTE2MyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE4NjMxNDYzNzA5XCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
