const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email =""
global.location="Taraba,Nigeria."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://www.peakpx.com/en/hd-wallpaper-desktop-fsqau.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "2348107052326" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2348107052326";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '4',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,null";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" ,
  
  author : process.env.PACK_AUTHER|| "JOSEPH-CM",
  packname: process.env.PACK_NAME || "STICKER",
  botname : process.env.BOT_NAME  || "JOSEPH-MD",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_07_40_07_06_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzIsXG4gICAgICAgIDczLFxuICAgICAgICAzNSxcbiAgICAgICAgMTksXG4gICAgICAgIDEwMSxcbiAgICAgICAgMzQsXG4gICAgICAgIDIyMixcbiAgICAgICAgOTgsXG4gICAgICAgIDIzLFxuICAgICAgICAxNzMsXG4gICAgICAgIDI1MCxcbiAgICAgICAgNjUsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMTM1LFxuICAgICAgICAyMjgsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTA3LFxuICAgICAgICA5NixcbiAgICAgICAgMjIzLFxuICAgICAgICA4OCxcbiAgICAgICAgMzcsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTIsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjEzLFxuICAgICAgICAyMixcbiAgICAgICAgMjEwLFxuICAgICAgICAxMzAsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTU5LFxuICAgICAgICAyNDQsXG4gICAgICAgIDkxXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI1MSxcbiAgICAgICAgNDksXG4gICAgICAgIDE3NixcbiAgICAgICAgMjU0LFxuICAgICAgICAxMTUsXG4gICAgICAgIDExMCxcbiAgICAgICAgNDgsXG4gICAgICAgIDg0LFxuICAgICAgICAyNSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxNDUsXG4gICAgICAgIDg5LFxuICAgICAgICAxMTIsXG4gICAgICAgIDEyLFxuICAgICAgICAxODIsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTksXG4gICAgICAgIDEyMyxcbiAgICAgICAgNDIsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTk0LFxuICAgICAgICA4LFxuICAgICAgICAxNDQsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMzAsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTA2LFxuICAgICAgICAxNTIsXG4gICAgICAgIDIxLFxuICAgICAgICAyMTUsXG4gICAgICAgIDEwNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA0LFxuICAgICAgICA1MCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAyNTAsXG4gICAgICAgIDgyLFxuICAgICAgICAxNTUsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMTg4LFxuICAgICAgICA2MixcbiAgICAgICAgMjQ5LFxuICAgICAgICAyMTcsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTU3LFxuICAgICAgICAxODAsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjAyLFxuICAgICAgICA3MCxcbiAgICAgICAgMjA4LFxuICAgICAgICA0NSxcbiAgICAgICAgNjAsXG4gICAgICAgIDY0LFxuICAgICAgICAxMjIsXG4gICAgICAgIDE0NyxcbiAgICAgICAgNjQsXG4gICAgICAgIDIyLFxuICAgICAgICA0NyxcbiAgICAgICAgMjUxLFxuICAgICAgICA2MixcbiAgICAgICAgMTg5LFxuICAgICAgICAxMyxcbiAgICAgICAgMTAxLFxuICAgICAgICAxMjBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMixcbiAgICAgICAgMTAxLFxuICAgICAgICAxNDYsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTc5LFxuICAgICAgICAxOTcsXG4gICAgICAgIDk3LFxuICAgICAgICAxMzMsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTk0LFxuICAgICAgICA5OSxcbiAgICAgICAgMTI3LFxuICAgICAgICAyMDYsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjE3LFxuICAgICAgICA2OSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxNjcsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjUzLFxuICAgICAgICA2MixcbiAgICAgICAgMTE5LFxuICAgICAgICA4MSxcbiAgICAgICAgMTYwLFxuICAgICAgICAyNDksXG4gICAgICAgIDI0NixcbiAgICAgICAgMTE3LFxuICAgICAgICAxMjQsXG4gICAgICAgIDE4LFxuICAgICAgICAxMDUsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM2LFxuICAgICAgICAyNDAsXG4gICAgICAgIDEwNSxcbiAgICAgICAgOTAsXG4gICAgICAgIDE0MixcbiAgICAgICAgOTMsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMjMyLFxuICAgICAgICAxMTksXG4gICAgICAgIDY3LFxuICAgICAgICA2NCxcbiAgICAgICAgNDksXG4gICAgICAgIDQ0LFxuICAgICAgICAyNDYsXG4gICAgICAgIDEyOCxcbiAgICAgICAgNDEsXG4gICAgICAgIDExMSxcbiAgICAgICAgNCxcbiAgICAgICAgNTMsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMCxcbiAgICAgICAgNyxcbiAgICAgICAgNCxcbiAgICAgICAgODEsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTAsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTksXG4gICAgICAgIDgzLFxuICAgICAgICA1MCxcbiAgICAgICAgMzgsXG4gICAgICAgIDEwNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjgsXG4gICAgICAgIDI0LFxuICAgICAgICA5OCxcbiAgICAgICAgMTYzLFxuICAgICAgICAxMjMsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjUxLFxuICAgICAgICA4LFxuICAgICAgICAyMjcsXG4gICAgICAgIDE1MCxcbiAgICAgICAgNTAsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjIyLFxuICAgICAgICA0OSxcbiAgICAgICAgMTEsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTEzLFxuICAgICAgICA4NSxcbiAgICAgICAgODksXG4gICAgICAgIDQ1LFxuICAgICAgICAxMjgsXG4gICAgICAgIDQwLFxuICAgICAgICAxMjcsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTY5LFxuICAgICAgICAyMjQsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTI1LFxuICAgICAgICA3MixcbiAgICAgICAgMTI2LFxuICAgICAgICAyMzcsXG4gICAgICAgIDY0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDksXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDksXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAxOTAsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICA5NSxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgNDEsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgNixcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgNzVcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgOCxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgNzFcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2MSxcbiAgICAgICAgMTAxLFxuICAgICAgICAxNDcsXG4gICAgICAgIDI1MCxcbiAgICAgICAgNzUsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMjA1LFxuICAgICAgICAxMjYsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTA0LFxuICAgICAgICAxNixcbiAgICAgICAgMjcsXG4gICAgICAgIDUwLFxuICAgICAgICA5NCxcbiAgICAgICAgOTcsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTkwLFxuICAgICAgICA0OSxcbiAgICAgICAgNzQsXG4gICAgICAgIDExMyxcbiAgICAgICAgMzMsXG4gICAgICAgIDE4MyxcbiAgICAgICAgOTAsXG4gICAgICAgIDYxLFxuICAgICAgICAzMSxcbiAgICAgICAgMjUsXG4gICAgICAgIDg2LFxuICAgICAgICA5NSxcbiAgICAgICAgMixcbiAgICAgICAgMTcwLFxuICAgICAgICA2OCxcbiAgICAgICAgMzksXG4gICAgICAgIDM1LFxuICAgICAgICA0OSxcbiAgICAgICAgMzgsXG4gICAgICAgIDUyLFxuICAgICAgICAxNjUsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTA3LFxuICAgICAgICAxOTIsXG4gICAgICAgIDExNSxcbiAgICAgICAgMzUsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMzcsXG4gICAgICAgIDI1NCxcbiAgICAgICAgNDQsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTYxLFxuICAgICAgICAxNDEsXG4gICAgICAgIDQzLFxuICAgICAgICAyMixcbiAgICAgICAgMTAxLFxuICAgICAgICA2OCxcbiAgICAgICAgMTk4LFxuICAgICAgICA3MSxcbiAgICAgICAgODgsXG4gICAgICAgIDQyLFxuICAgICAgICAxNCxcbiAgICAgICAgMjQ2LFxuICAgICAgICA0OSxcbiAgICAgICAgMjIyLFxuICAgICAgICAyMDEsXG4gICAgICAgIDE5NSxcbiAgICAgICAgNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogNjAsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiNENPZGJKazFjanFKSk13WUJBQjRFRzFyaVRFUnBMblVTUGNlT0FhWmE2VT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MTA3MDUyMzI2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIxRjk4ODRGMDYzREVBRjcyQTJDOTVENDE0ODVCREM4Q1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAyNTE2NDVcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MTA3MDUyMzI2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIyNkRFMzlENUZFOTIxNjhDQUZFQTUyMzU0MTkwRkFGRVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAyNTE2NDZcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiTW9xS0NVejZTVU9jaUF2OGFzRUxzQVwiLFxuICBcInBob25lSWRcIjogXCI2YmE2YzVjNy04YjE0LTQyZDAtYjc5OC1mMjA2MzkwNjg1MWJcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTU0LFxuICAgICAgOTQsXG4gICAgICAxMjksXG4gICAgICA0OSxcbiAgICAgIDE0NCxcbiAgICAgIDUxLFxuICAgICAgNDMsXG4gICAgICAxMzQsXG4gICAgICA3NyxcbiAgICAgIDE1MSxcbiAgICAgIDYsXG4gICAgICAxMTYsXG4gICAgICAxMDMsXG4gICAgICAyMTEsXG4gICAgICAyNDAsXG4gICAgICA1MSxcbiAgICAgIDkwLFxuICAgICAgODksXG4gICAgICAyMDQsXG4gICAgICAyMTRcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMzYsXG4gICAgICAxODMsXG4gICAgICAyNDAsXG4gICAgICAxMDcsXG4gICAgICAzNSxcbiAgICAgIDIwNCxcbiAgICAgIDEwNCxcbiAgICAgIDI0OSxcbiAgICAgIDIxOSxcbiAgICAgIDE1OCxcbiAgICAgIDgxLFxuICAgICAgMTA5LFxuICAgICAgMTQ0LFxuICAgICAgMjExLFxuICAgICAgMjE2LFxuICAgICAgMTU0LFxuICAgICAgMTUyLFxuICAgICAgMjExLFxuICAgICAgMjksXG4gICAgICAxNDFcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiS1RISldLQ0FcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDgxMDcwNTIzMjY6MTZAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJK4buMzIFTM1BIIE1BRFVLQVwiLFxuICAgIFwibGlkXCI6IFwiMTc0MTk5OTk3OTk3MTcyOjE2QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0x5TGllOERFUFhwbzdRR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiOVlXdWhJcUlTaUZaZEJ4alNDNk9EeUNDUTB1eURUSlFwVUkxRXQvYTRDZz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJEZ3RoRVlWR3dqN2lxcDVHUmZQYlZZRitwbkJaMGdISHA4eTE5ZU9GbklzdXJkWVlPZTFGWnJjNDJJQTAxR1ZDU2hGbk04MUNNenZKeHhyV2RyZU5Edz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJBNkpqSktlNUo0VkxRc3hKL25lSm9oZU1mNmJLaU8yS2xKTStqM3BhdzFPT3Z0UnRtUUpoQnJQY2VGYTRMVFhxZjF4NnVFZGFoRW5idE5TYlhIV1BEQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ4MTA3MDUyMzI2OjE2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAzMixcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICA2NixcbiAgICAgICAgICA1MyxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICA0MFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIwMjUxNjQwLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBTlpwXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFOWnAuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJCT2puM0s5cUNrOEtkcW5QOUhjQkNtMk1wMk40bE1TaDc0OFZxemxUZXFzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEwMzgyMzkxNjQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyMDI1MTY0MzA0MlwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
